### Get all Professionals
GET http://localhost:8080/api/professionals
Accept: application/json

### Get a professional by a given id.
GET http://localhost:8080/api/professionals/6

### Delete a professional by a given id.
DELETE http://localhost:8080/api/professionals/6

### Add a new professional to the database.
POST http://localhost:8080/api/professionals
Content-Type: application/json

{"name":"Sammy","description": "Passionate about his work",
  "rating": 8, "location": "Westerville", "online": false,
  "specialty": "Barber", "phoneNumber": "5555555555", "payment": "cash",
"daysOfOperation": "Weekdays"}

### Update pro resource
PUT http://localhost:8080/api/professionals/7
Content-Type: application/json

{"name":"Sammy","description": "Passionate about his work",
  "rating": 8, "location": "Westerville", "online": false,
  "specialty": "Barber", "phoneNumber": "5555555555", "payment": "cash",
  "daysOfOperation": "Weekdays"}

### Add a review to a professional
PATCH http://localhost:8080/api/professionals/7/reviews

Great style!

### Add a photo to a professional
PATCH http://localhost:8080/api/professionals/7/photos

https://imgur.com/PqRtRuO

### Update a rating properity of a professional. Still not working
PUT http://localhost:8080/api/professionals/7/rating

8.4

### Add a new service to a professional.
PATCH http://localhost:8080/api/professionals/7/serves
Content-Type: application/json

{"serveName": "New Service",
  "serveDescription": "New Service Description",
  "price": 7.95}